export const frameworkOptions = [
  {
    label: 'React',
    value: 'react',
    logo: null,
    // color: 'bg-blue-500',
    // fontColor: 'text-sky-500',
  },
  {
    label: 'Preact',
    value: 'preact',
    logo: null,
    // color: 'bg-purple-500',
    // fontColor: 'text-purple-500',
  },
  {
    label: 'Vue',
    value: 'vue',
    logo: null,
    // color: 'bg-green-500',
    // fontColor: 'text-green-500',
  },
  {
    label: 'Angular',
    value: 'angular',
    logo: null,
    // color: 'bg-red-500',
    // fontColor: 'text-fuchsia-500',
  },
  {
    label: 'Solid',
    value: 'solid',
    logo: null,
    // color: 'bg-blue-600',
    // fontColor: 'text-blue-600',
  },
  {
    label: 'Lit',
    value: 'lit',
    logo: null,
    // color: 'bg-emerald-500',
    // fontColor: 'text-emerald-500',
  },
  {
    label: 'Svelte',
    value: 'svelte',
    logo: null,
    // color: 'bg-orange-600',
    // fontColor: 'text-orange-600',
  },
  {
    label: 'Qwik',
    value: 'qwik',
    logo: null,
    // color: 'bg-indigo-500',
    // fontColor: 'text-indigo-500',
  },
  {
    label: 'Vanilla',
    value: 'vanilla',
    logo: null,
    // color: 'bg-yellow-500',
    // fontColor: 'text-yellow-500',
  },
] as const
